# -*- coding: utf-8 -*-
"""DeepLearning_kaggle(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sl6X2M4xJdJBMPELKmF8974mwb5_rqUh
"""

import kagglehub
import shutil

# Download latest version
path = kagglehub.dataset_download("eldadvikorian/dataset-sampah-organik-dan-anorganik")

# Define the destination path
destination_path = "/content"

# Move files to the destination
shutil.move(path, destination_path)

print("Path to dataset files:", destination_path)

path = "/content/1/DATASET"
destination = "/content"
shutil.move(path, destination)

#import shutil

# Ganti 'dataset_model' dengan nama folder yang ingin Anda hapus
#folder_path = '/content/1'
#shutil.rmtree(folder_path)

# prompt: mengetahui berapa data di TEST dan dimasing masing subfolder. dan berapa data di TRAIN dan dimasing masing subflodernya

import os

def count_files_in_folders(root_folder):

  file_counts = {}
  for dirpath, dirnames, filenames in os.walk(root_folder):
    folder_name = os.path.basename(dirpath)
    file_counts[folder_name] = len(filenames)
  return file_counts


# Example usage:
train_counts = count_files_in_folders("/content/DATASET/TRAIN")
test_counts = count_files_in_folders("/content/DATASET/TEST")

print("Number of files in TRAIN folders:")
for folder, count in train_counts.items():
    print(f"  {folder}: {count}")

print("\nNumber of files in TEST folders:")
for folder, count in test_counts.items():
    print(f"  {folder}: {count}")

total_train = sum(train_counts.values())
total_test = sum(test_counts.values())

print(f"\nTotal files in TRAIN: {total_train}")
print(f"Total files in TEST: {total_test}")

# Import necessary libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Paths to train and test folders
train_dir = "/content/DATASET/TRAIN"
test_dir = "/content/DATASET/TEST"

# Image data generators with augmentation for the training data
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
)

test_datagen = ImageDataGenerator(rescale=1.0/255)

batch_size = 16
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),
    batch_size=batch_size,
    class_mode='binary'
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(150, 150),
    batch_size=batch_size,
    class_mode='binary'
)

# CNN model definition
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Training the model with fewer steps per epoch and more epochs
steps_per_epoch = 200
history = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,
    epochs=100,
    validation_data=test_generator
)

# Evaluate the model
test_loss, test_accuracy = model.evaluate(test_generator)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

# prompt: buat plot akurasi model CNN

import matplotlib.pyplot as plt

# Plot training & validation accuracy values
plt.figure(figsize=(10, 5))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# Plot training & validation loss values
plt.figure(figsize=(10, 5))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# prompt: buat untuk tampilan ROC curve

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np

# ... (Your existing code) ...

# Predict probabilities on the test set
y_pred_prob = model.predict(test_generator)

# Get true labels
y_true = test_generator.classes

# Compute ROC curve and ROC area for each class
fpr, tpr, _ = roc_curve(y_true, y_pred_prob)
roc_auc = auc(fpr, tpr)

# Plot of a ROC curve for a specific class
plt.figure()
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], 'k--')  # Random guessing line
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()

# prompt: Laporan evaluasi dengan precision, recall, F1-score

from sklearn.metrics import classification_report

# Make predictions on the test set
predictions = model.predict(test_generator)
predicted_classes = (predictions > 0.5).astype(int)

# Get true labels
true_classes = test_generator.classes

# Generate classification report
report = classification_report(true_classes, predicted_classes, target_names=['organic', 'inorganic'])
report

# prompt: # Confusion Matrix

from sklearn.metrics import confusion_matrix
import seaborn as sns

# Generate confusion matrix
cm = confusion_matrix(true_classes, predicted_classes)

# Plot confusion matrix using seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['organic', 'inorganic'],
            yticklabels=['organic', 'inorganic'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# prompt: # Memuat dan mengklasifikasikan gambar baru dengan upload gambar dan tunjukkan berapa persen kebenarannya

from google.colab import files
import numpy as np
from PIL import Image

uploaded = files.upload()

for fn in uploaded.keys():
  path = fn
  img = Image.open(path).convert("RGB")
  img = img.resize((150,150))
  img_array = np.array(img) / 255.0
  img_array = np.expand_dims(img_array, axis=0)

  prediction = model.predict(img_array)
  predicted_class = (prediction > 0.5).astype(int)[0][0]
  confidence = prediction[0][0]

  if predicted_class == 0:
    predicted_label = "organic"
  else:
    predicted_label = "inorganic"

  print(f"Prediction: {predicted_label} ({confidence * 100:.2f}%)")